import { ToastContainer } from "react-toastify";
import BlogList from "@/Components/BlogList";
import Footer from "@/Components/Footer";
import Header from "@/Components/Header";
import "react-toastify/dist/ReactToastify.css";

import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

interface HomeLayoutProps {
  children: React.ReactNode;
}

export default function HomeLayout({ children }: HomeLayoutProps): React.ReactElement {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ToastContainer theme="dark" />
        <Header />
        <main>{children || <BlogList />}</main>
        <Footer />
      </body>
    </html>
  );
}
